# Generated by Django 3.0.3 on 2020-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='Class',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='school_id',
            field=models.IntegerField(default=1),
        ),
    ]
