# Generated by Django 3.0.3 on 2020-05-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_school', '0002_auto_20200520_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='student_name',
            field=models.CharField(default='Name', max_length=30),
        ),
    ]
